config/routes.rb
Todev::Application.routes.draw do
  
  
  resources :carts

  resources :proitems

  resources :products do
    resources :proitems , :only => [:create]
  end

  resources :properties

  resources :attris

  devise_for :users

  resources :posts

  resources :profiles

  get "home/index"
root :to => "posts#index"

end

app/models/proitem.rb
class Proitem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  attr_accessible :someline,:product_id
  validates  :someline,:product_id, :presence => true
end

app/controllers/proitems_controller.rb
class ProitemsController < ApplicationController
  # GET /proitems
  # GET /proitems.json
  def index
    @proitems = Proitem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @proitems }
    end
  end

  # GET /proitems/1
  # GET /proitems/1.json
  def show
    @proitem = Proitem.find(params[:id])

    k = @proitem.someline.split(',')

    @prop = Property.find(k)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @proitem }
    end
  end

  # GET /proitems/new
  # GET /proitems/new.json
  def new
    @proitem = Proitem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @proitem }
    end
  end

  # GET /proitems/1/edit
  def edit
    @proitem = Proitem.find(params[:id])
  end

  # POST /proitems
  # POST /proitems.json
  def create
    #@proitem = Proitem.new(params[:proitem])
    #@product = Product.find(params[:product_id])
    #@proitem = Proitem.new(:product_id => @product.id)
    @cart = current_cart
    @product = Product.find(params[:product_id])
    #someline = params[:proitem_someline]
    #@proitem = @cart.proitems.build(:product_id => @product.id, :someline => someline)
    @proitem = @cart.proitems.create(params[:proitem])
    respond_to do |format|
      if @proitem.save
        format.html { redirect_to @product, notice: 'Proitem was successfully created.' }
        format.json { render json: @proitem, status: :created, location: @proitem }
      else
        format.html { render action: "new" }
        format.json { render json: @proitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /proitems/1
  # PUT /proitems/1.json
  def update
    @proitem = Proitem.find(params[:id])

    respond_to do |format|
      if @proitem.update_attributes(params[:proitem])
        format.html { redirect_to @proitem, notice: 'Proitem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @proitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proitems/1
  # DELETE /proitems/1.json
  def destroy
    @proitem = Proitem.find(params[:id])
    @proitem.destroy

    respond_to do |format|
      format.html { redirect_to proitems_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/proitems_helper.rb
module ProitemsHelper
end

app/views/proitems/_form.html.erb
<%= simple_form_for(@proitem) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :product %>
    <%= f.input :someline %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/proitems/edit.html.erb
<h1>Editing proitem</h1>

<%= render 'form' %>

<%= link_to 'Show', @proitem %> |
<%= link_to 'Back', proitems_path %>

app/views/proitems/index.html.erb
<h1>Listing proitems</h1>

<table>
  <tr>
    <th>Product</th>
    <th>Someline</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @proitems.each do |proitem| %>
  <tr>
	  <td><%= proitem.id %></td>
    <td><%= link_to 'GOTOPRODUCT', product_path(proitem.product, :k => proitem.id) %></td>
	<td><%= proitem.product.id unless proitem.product.blank? %></td>
    <td><%= proitem.someline %></td>
    <td><%= link_to 'Show', proitem %></td>
    <td><%= link_to 'Edit', edit_proitem_path(proitem) %></td>
    <td><%= link_to 'Destroy', proitem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Proitem', new_proitem_path %>

app/views/proitems/new.html.erb
<h1>New proitem</h1>

<%= render 'form' %>

<%= link_to 'Back', proitems_path %>

app/views/proitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  #<%= @proitem.product.id %>
  <%= @proitem.product.name %>
</p>

<p> Product2 Meta: <br> 

<% @prop.each do |a| %>
	<li><%= a.attri.name%> : <%= a.name %></li>
<% end %>

</p>


<p>
  <b>Someline:</b>
  <%= @proitem.someline.split(",") %>
  <%= @product.id  %>
  <%#= @prop.each do |p| %>
  <%#= "#{p.attri.name} :#{p.name}" %> <br>
  <%#end -%>
</p>


<%= link_to 'Edit', edit_proitem_path(@proitem) %> |
<%= link_to 'Back', proitems_path %>